### ISSUE TITLE
dotnet restore is giving error while creating an image for asp.net core application

### ISSUE THREAD

**Issue by pabitra** [aspnet/aspnet-docker#147]
**Output of docker version:

` Docker version 1.12.1, build 23cf638

**Output of `docker info`:**

Containers: 33
Running: 2
Paused: 0
Stopped: 31
Images: 40
Server Version: 1.12.1
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 93
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-46-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.854 GiB
Name: ubuntu
ID: G5QL:IICX:YZ6K:BFEP:25U4:TYZY:II6P:XEEX:4HVV:KTZH:GLNK:N4KZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. install docker on Ubuntu 14.0.
2. asp.net core
3. create a new sample using dotnet new
4. docker build -t dockersample .
5 Docker file : 
    FROM microsoft/dotnet:latest
    COPY project.json /app/
    WORKDIR /app
    COPY . /app
    RUN ["dotnet", "restore"]
    EXPOSE 5004/tcp
    ENTRYPOINT ["dotnet", "run"]

**Describe the results you received:**
Unhandled Exception: Microsoft.DotNet.ProjectModel.FileFormatException: unknown keyword platform ---> System.InvalidOperationException: unknown keyword platform
   at Microsoft.DotNet.ProjectModel.Graph.LibraryDependencyType.Parse(String keyword)
   at Microsoft.DotNet.ProjectModel.ProjectReader.PopulateDependencies(String projectPath, IList`1 results, JsonObject settings, String propertyName, Boolean isGacOrFrameworkReference)
   at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics, Settings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   at Microsoft.DotNet.ProjectModel.ProjectContextBuilder.ResolveProject(String projectDirectory)
   at Microsoft.DotNet.ProjectModel.ProjectContextBuilder.EnsureProjectLoaded()
   at Microsoft.DotNet.ProjectModel.ProjectContextBuilder.Build()
   at Microsoft.DotNet.ProjectModel.ProjectContext.Create(String projectPath, NuGetFramework framework, IEnumerable`1 runtimeIdentifiers)
   at Microsoft.DotNet.ProjectModel.ProjectContext.Create(String projectPath, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Utils.Command.ResolveExecutablePathFromProject(String executable, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Utils.Command.ResolveExecutablePath(String& executable, String& args, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

The command 'dotnet restore' returned a non-zero code: 139

**Describe the results you expected:**
image should be created with dotnet restore

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by sesispla** [comment]
Annoying issue. 

It rose again when building .NET Core in Kuberntes + CoreOS. From 30 builds, only 4 ended successfully. I tried to disable parallel download with "dotnet restore --disable-parallel" with no luck.

Some error codes I have received:
```
Step 4 : RUN dotnet restore
 ---> Running in f07a30a37533
log  : Restoring packages for /app/project.json...
error: Object reference not set to an instance of an object.
The command 'dotnet restore' returned a non-zero code: 1
```

```
Step 4 : RUN dotnet restore
 ---> Running in 2ed896ccf03b
log  : Restoring packages for /app/project.json...
The command 'dotnet restore' returned a non-zero code: 139
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

```
Step 4 : RUN dotnet restore --disable-parallel
 ---> Running in 7d7191579a3a
log  : Restoring packages for /app/project.json...
The command 'dotnet restore --disable-parallel' returned a non-zero code: 139
Build step 'Execute shell' marked build as failure
```

Randomly, the package restore ends successfully:

```
Step 4 : RUN dotnet restore --disable-parallel
 ---> Running in f0678a4802b9
log  : Restoring packages for /app/project.json...
log  : ...
log  : Writing lock file to disk. Path: /app/project.lock.json
log  : /app/project.json
log  : Restore completed in 16025ms.
 ---> 48c5e1096006
Removing intermediate container f0678a4802b9
Step 5 : RUN dotnet build
 ---> Running in 710b04add816
Project app (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling app for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.4904282
```

Once I even got the exact error code at build time:
```
Step 5 : RUN dotnet build
 ---> Running in a5d1a0b9526c
Project app (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling app for .NETCoreApp,Version=v1.0
[91m/usr/share/dotnet/dotnet compile-csc @/app/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 139
[0m
Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.6820830

The command 'dotnet build' returned a non-zero code: 1
```

**Comment by glennc** [comment]
These latest issues don't appear to be related the original post.

Something strange is definitely happening, but I don't know what. Perhaps @piotrpMSFT or @blackdwarf can help diagnose why the CLI is failing seemingly at random.

**Comment by muratg** [comment]
@sesispla What image are you using?

**Comment by glennc** [comment]
Closing due to lack of activity. I don't think there is anything for us to do here, I think that it is a bug in the CLI tools that are being run that happens to surface inside a container. But we can't really verify that without more people who are hitting it helping us diagnose where the problem is to get the right people involved.

**Comment by lalitkale** [comment]
This is not right to close the issue without fixing it. I am still facing this issue on my windows 10 preview builds and docker 1.13.1 (channel:stable)

**Comment by glennc** [comment]
@lalitkale Whilst this repo is where we have the code to build the ASP.NET Core docker images, the examples given either don't say what image they are using are not using the images from this repo. The errors are also not likely to actually be caused by being inside a container even if they where. The CLI https://github.com/dotnet/cli or NuGet https://github.com/NuGet/Home repositories are more appropriate for bugs about restore or build, which is what this appears to be. Given that you haven't provided any information about which of the two different issues people have seen in this thread I can't say which you should create an issue on. But the CLI would be a reasonable start if you want to try and help the dev team track down the cause of the issues.

**Comment by lalitkale** [comment]
@glennc Thank you for responding on this. I will file an issue on cli repo with details. Give me a day or two.
