### ISSUE TITLE
dotnet publish doesn't work properly with absolute output directory

### ISSUE THREAD

**Issue by Nagarian** [aspnet/aspnet-docker#356]
Hi, I've recently faced a strange issue with the `dotnet publish` command. If we try to build our container with an absolute output directory path, the command process successfully, but some dll differs in size and so when we launch the command `dotnet MyProject.dll` we are facing the error :
```bash
root@c36d47fb5c51:/out# dotnet MyProject.dll

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at MyProject.Program.Main(String[] args) in /src/MyProject/Program.cs:line 35
Aborted (core dumped)
```
And if we change it to a relative path, everything works properly.

## Steps to reproduce the issue
```Dockerfile
FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY MyProject/MyProject.csproj MyProject/MyProject.csproj
COPY MyProject.ActiveDirectory.NETStandard/MyProject.ActiveDirectory.NETStandard.csproj MyProject.ActiveDirectory.NETStandard/MyProject.ActiveDirectory.NETStandard.csproj
COPY *.sln ./
RUN dotnet restore

COPY . ./
# doesn't work
RUN dotnet publish -c Release -o /out
# work
RUN dotnet publish -c Release -o out

FROM microsoft/aspnetcore:2.0
WORKDIR /app
EXPOSE 80
# COPY --from=build /out ./
COPY --from=build /src/MyProject/out ./
ENTRYPOINT ["dotnet", "MyProject.dll"]
```

## Expected behavior
```bash
root@9d6a93f7b71a:/src# ls -la /out/
total 17956
drwxr-xr-x  4 root root   12288 Jan 22 21:32 .
drwxr-xr-x 72 root root    4096 Jan 22 21:33 ..

-rw-r--r--  1 root root   36360 Jan  9 16:58 Microsoft.Extensions.DependencyInjection.Abstractions.dll

-rw-r--r--  1 root root   46600 Jan  9 16:58 Microsoft.Extensions.Logging.Abstractions.dll

-rw-r--r--  1 root root   16904 Jan  9 16:58 Microsoft.Extensions.Logging.Debug.dll
-rw-r--r--  1 root root   30728 Jan  9 16:58 Microsoft.Extensions.Logging.dll

drwxr-xr-x 12 root root    4096 Jan 22 21:35 runtimes
```

## Actual behavior
```bash
root@9d6a93f7b71a:/src# ls -la /out/
total 17956
drwxr-xr-x  4 root root   12288 Jan 22 21:32 .
drwxr-xr-x 72 root root    4096 Jan 22 21:33 ..
-rw-r--r--  1 root root   57779 Jan 22 21:32 MyProject.ActiveDirectory.NETStandard.deps.json

-rwxrw-rw-  1 root root   35840 Jun 22  2016 Microsoft.Extensions.DependencyInjection.Abstractions.dll

-rwxrw-rw-  1 root root   43512 Jun 22  2016 Microsoft.Extensions.Logging.Abstractions.dll

-rwxrw-rw-  1 root root   16376 Jun 22  2016 Microsoft.Extensions.Logging.Debug.dll
-rwxrw-rw-  1 root root   18424 Jun 22  2016 Microsoft.Extensions.Logging.dll

-rw-r--r--  1 root root   27320 Jan  9 16:58 System.Buffers.dll
-rw-r--r--  1 root root   93432 Jan  9 16:58 System.Collections.Concurrent.dll
-rw-r--r--  1 root root   88472 Jan  9 16:58 System.Collections.NonGeneric.dll
-rwxrw-rw-  1 root root   21720 Jun 11  2016 System.ComponentModel.dll
-rw-r--r--  1 root root   35760 Jan  9 16:58 System.Diagnostics.DiagnosticSource.dll
-rw-r--r--  1 root root   29592 Jan  9 16:58 System.IO.Compression.ZipFile.dll
-rw-r--r--  1 root root   22432 Jan  9 16:58 System.IO.FileSystem.Primitives.dll

-rwxrw-rw-  1 root root   32504 Jun 11  2016 System.Net.WebHeaderCollection.dll
-rw-r--r--  1 root root   49352 Jan  9 16:58 System.ObjectModel.dll

-rw-r--r--  1 root root   22352 Jan  9 16:58 System.Runtime.InteropServices.RuntimeInformation.dll
-rw-r--r--  1 root root   71392 Jan  9 16:58 System.Runtime.Numerics.dll
-rwxrw-rw-  1 root root   57720 Jun 11  2016 System.Security.Claims.dll
-rw-r--r--  1 root root   45504 Jan  9 16:58 System.Security.Cryptography.Primitives.dll

-rw-r--r--  1 root root   21736 Jan  9 16:58 System.Security.Principal.dll

-rw-r--r--  1 root root   25864 Jan  9 16:58 System.Threading.Tasks.Extensions.dll
-rw-r--r--  1 root root   22400 Jan  9 16:58 System.Threading.Thread.dll
-rw-r--r--  1 root root   22416 Jan  9 16:58 System.Threading.ThreadPool.dll
-rw-r--r--  1 root root   50016 Jan  9 16:58 System.Threading.dll
-rw-r--r--  1 root root  606592 Jan  9 16:58 System.Xml.ReaderWriter.dll
-rw-r--r--  1 root root  111312 Jan  9 16:58 System.Xml.XDocument.dll

drwxr-xr-x 22 root root    4096 Jan 22 21:32 runtimes
```

## Additional information (e.g. issue happens only occasionally)
Note that the output differs by theses dll sizes. 

## Output of `dotnet --info`

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

## Output of `docker info`

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 60
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.916GiB
Name: vps418168.ovh.net
ID: TBBX:VVQH:PWSS:QUCM:O4JF:37Y3:KVDF:POE7:VBWN:MWUA:3G4V:VKOA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by natemcmaster** [comment]
@Nagarian it doesn't appear to me that this issue is specific to Docker. Can you move this issue to https://github.com/dotnet/cli instead?
